version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: shoppy
    restart: unless-stopped
    environment:
      POSTGRES_DB: shoppy_db
      POSTGRES_USER: shoppy_user
      POSTGRES_PASSWORD: shoppy_password
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
